apiVersion: v1
kind: Service
metadata:
  name: ms-eventos-service
spec:
  selector:
    app: ms-eventos
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30090
  type: NodePort