apiVersion: v1
kind: Service
metadata:
  name: oracle-db-service
spec:
  type: NodePort
  selector:
    app: oracle-db
  ports:
    - name: oracle
      protocol: TCP
      port: 1521
      targetPort: 1521
      nodePort: 30011