services:
  dki-oradb:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: dki-oradb
    environment:
      ORACLE_PWD: del1al9
      ORACLE_SID: XE
      ORACLE_PDB: XEPDB1
      ORACLE_CHARACTERSET: AL32UTF8
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ms-volume:/opt/oracle/oradata
      - ./oracle:/opt/oracle/scripts/startup
    networks:
      - ms-network
    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus system/del1al9@localhost:1521/XE"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  ms-eventos:
    image: ms-eventos:v1
    container_name: ms-eventos
    build:
      context: ../ms-eventos
    ports:
      - "9090:9090"
    networks:
      - ms-network
    depends_on:
      dki-oradb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9090/eventos"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  ms-participantes:
    image: ms-participantes:v1
    container_name: ms-participantes
    build:
      context: ../ms-participantes
    ports:
      - "7075:7075"
    environment:
      - MS_EVENTOS_URL=http://ms-eventos:9090
    networks:
      - ms-network
    depends_on:
      dki-oradb:
        condition: service_healthy
      ms-eventos:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:7075/participante"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

volumes:
  ms-volume:

networks:
  ms-network:
    driver: bridge
