apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-eventos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-eventos
  template:
    metadata:
      labels:
        app: ms-eventos
    spec:
      containers:
      - name: ms-eventos-container
        image: anthonyponte/ms-eventos:v4
        ports:
        - containerPort: 9090
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: ms-eventos-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ms-eventos-secret
              key: DB_PASSWORD
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: ms-eventos-configmap
              key: APP_NAME
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: ms-eventos-configmap
              key: SERVER_PORT
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: ms-eventos-configmap
              key: DB_URL
        - name: DB_DRIVER
          valueFrom:
            configMapKeyRef:
              name: ms-eventos-configmap
              key: DB_DRIVER
        - name: JPA_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: ms-eventos-configmap
              key: JPA_DDL_AUTO
        - name: JPA_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: ms-eventos-configmap
              key: JPA_SHOW_SQL
        - name: HIBERNATE_DIALECT
          valueFrom:
            configMapKeyRef:
              name: ms-eventos-configmap
              key: HIBERNATE_DIALECT