ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER dkuser IDENTIFIED BY dkpassword;
GRANT CONNECT, RESOURCE TO dkuser;

ALTER USER dkuser QUOTA UNLIMITED ON users;

CREATE TABLE dkuser.eventos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(125) NOT NULL,
    nombre VARCHAR2(255) NOT NULL,
    descripcion VARCHAR2(255) NOT NULL,
    fecha DATE NOT NULL,
    ubicacion VARCHAR2(255) NOT NULL,
    capacidad_max INT NOT NULL
);

CREATE TABLE dkuser.participantes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento NUMBER NOT NULL,
    dni VARCHAR2(8) NOT NULL,
    nombres_apellidos VARCHAR2(255) NOT NULL,
    fecha_registro DATETIME NOT NULL
);

ALTER TABLE dkuser.participantes
ADD CONSTRAINT fk_participantes_eventos
FOREIGN KEY (id_evento)
REFERENCES dkuser.eventos(id);