apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-participantes
  labels:
    app: ms-participantes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-participantes
  template:
    metadata:
      labels:
        app: ms-participantes
    spec:
      containers:
        - name: ms-participantes
          image: anthonyponte/ms-participantes:v1
          args:
            - "--spring.config.additional-location=file:/config/"
          ports:
            - containerPort: 7075

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 7075
            initialDelaySeconds: 100
            periodSeconds: 30
            timeoutSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 7075
            initialDelaySeconds: 105
            periodSeconds: 15
            timeoutSeconds: 10

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

          resources:
            requests:
              cpu: "100m"
              memory: "300Mi"
            limits:
              cpu: "200m"
              memory: "500Mi"

          volumeMounts:
            - name: config-volume
              mountPath: /config/
              subPath: application.yml

      volumes:
        - name: config-volume
          configMap:
            name: ms-participantes-config
            items:
              - key: application.yml
                path: application.yml
