apiVersion: v1
kind: Service
metadata:
  name: ms-participantes-service
spec:
  selector:
    app: ms-participantes
  ports:
  - protocol: TCP
    port: 7075
    targetPort: 7075
    nodePort: 30075
  type: NodePort