ms-participantes:
    image: ms-participantes:1.2
    container_name: ms-participantes
    ports:
      - "7075:7075"
    environment:
      USER_DEMO: Netec
    networks:
      - dki-network
    depends_on:
      dki-oradb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9081/participantes"]
      interval: 30s
      timeout: 15s
      retries: 5

ms-eventos:
    image: ms-eventos:1.2
    container_name: ms-eventos
    ports:
      - "9090:9090"
    environment:
      MS_PARTICIPANTES_URL: http://ms-productos:7075/participantes
    networks:
      - dki-network
    depends_on:
      ms-participantes:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9090/eventos"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

volumes:
  dki-volume:

networks:
  dki-network:
    external: true
services:
  dki-oradb:
    container_name: dki-oradb
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      ORACLE_PWD: Netec_123
      ORACLE_SID: XE
      ORACLE_PDB: XEPDB1
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - dki-volume:/opt/oracle/oradata
      - ./scripts:/opt/oracle/scripts/startup
    networks:
      - dki-network
    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus system/Netec_123@localhost:1521/XE"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
