apiVersion: v1
kind: Service
metadata:
 name: ms-email
spec:
 type: NodePort
 ports:
   - port: 80
     targetPort: 8081
     nodePort: 30081  # Puedes especificar el NodePort o dejar que Kubernetes lo asigne.
 selector:
   app: ms-email
